{
 "title": "EHL-Reliability Monitoring Dashboard",
 "description": "This dashboard servers the purpose for monitoring reliability executions.",
 "time": { "from": "2020-02-29T18:30:00.000Z", "to": "2020-03-02T18:29:59.000Z" },
 "templating": {
  "list": [
   { "name": "RunName", "query": "select name from run;" },
   {
    "name": "RunID",
    "query": "Select id from run where name = '$RunName';"
   },
   {
    "name": "StartTime",
    "query": "select start_time from run where id = $RunID;"
   },
   {
    "name": "EndTime",
    "query": "select end_time from run where id = $RunID;"
   },
   { "name": "LockID", "query": "${VAR_LOCKID}" }
  ]
 },
 "panels": [
  { "title": "Execution Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "content": "<p style = \"font-family:Broadway;font-size:200%;text-align:center;weight:bold;color:#0000cc;background-color:#C4BFBE\">Reliability Monitoring Dashboard</p>\n\n\n\n\n\n"
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  build_details AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  release AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  description AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  run_type AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  name AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  run_status AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  environment AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Iterations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  id\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  run_id = $RunID\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'COMPLETED' AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'FAILED' AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Iteration Status Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Iterations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Iteration Status Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Iterations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'COMPLETED' AND\n  run_id = $RunID\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'FAILED' AND\n  run_id = $RunID\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'STARTED' AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Iteration Status Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  $LockID\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Incidents Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none", "label": "Iterations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(start_time) AND\n  status = 'FAILED' AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Incident Type Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_of_occurance AS \"time\",\n  incident_type AS metric,\n  iteration_id\nFROM incident\nWHERE\n  $__timeFilter(time_of_occurance) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Incident  Type Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  time_of_occurance AS \"time\",\n  incident_type AS metric,\n  $LockID\nFROM incident\nWHERE\n  $__timeFilter(time_of_occurance) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Incident Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_of_occurance AS \"time\",\n  message AS metric,\n  iteration_id\nFROM incident\nWHERE\n  $__timeFilter(time_of_occurance) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  }
 ]
}