{
 "title": "EHL- ServiceReliabilityDashboard",
 "description": "This dashboard servers the purpose for monitoring  Jmeter executions.",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   {
    "name": "Application",
    "label": "RunName",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   {
    "name": "TestName",
    "label": "ApplicationName",
    "query": "Select text from \"events\"  where  \"application\" =~ /^$Application$/"
   },
   {
    "name": "Transactions",
    "label": "Requests",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"transaction\" WHERE \"application\" =~ /^$Application$/ AND \"transaction\" != 'internal' AND \"transaction\" != 'all'"
   },
   { "name": "measurement_name", "label": "Measurement name", "query": "jmeter" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<p style = \"font-family:Broadway;font-size:200%;text-align:center;weight:bold;color:#0000cc;background-color:#C4BFBE\">Service Reliability Monitoring Dashboard</p>\n\n\n\n\n\n"
  },
  {
   "title": "Incidents Per Thousand Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "IPTR 50%",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\")  FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Passed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\")-sum(\"countError\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE ( \"application\" =~ /^$Application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Passed Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") -sum(\"countError\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Failed Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Errors",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"countError\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Success Rate %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 13 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"count\")-sum(\"countError\")  AS \"success\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate %",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM \"$measurement_name\" WHERE \"transaction\" = 'all' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "Throughput",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\") / $send_interval FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"hit\") / $send_interval FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Recieved Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"rb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "Send Bytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"sb\") FROM \"$measurement_name\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$Application$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Transactions Response Times (90th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (95th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times (99th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - Received Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"rb\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Traffic - Send Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sb\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Errors Information",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"responseCode\" !~ /^$/) AND $timeFilter GROUP BY  \"transaction\",\"responseCode\",\"responseMessage\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Individual Transaction - $Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 }
  },
  {
   "title": "Total Requests - $Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 83 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Passed Requests - $Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 83 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Failed Requests - $Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 83 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "IPTR 50% - $Transactions",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 83 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_name$/",
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times - $Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"avg\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct50.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "pct50.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "90th Percentile",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct90.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct90.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    },
    {
     "alias": "95th Percentile",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct95.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "99th Percentile",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct99.0\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct99.0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"max\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"min\") FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Request Percentage % - $Transactions",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 87 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE (\"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput - $Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Reqest/second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"count\") / $send_interval FROM \"$measurement_name\" WHERE (\"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$transaction$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Errors - $Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"$measurement_name\" WHERE \"application\" =~ /^$Application$/ AND \"transaction\" =~ /^$Transactions$/ AND \"statut\" = 'ko' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}