{
 "title": "Reliability Monitoring Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "RunName", "query": "select name from run;" },
   {
    "name": "RunID",
    "query": "Select id from run where name = '$RunName';"
   },
   {
    "name": "StartTime",
    "query": "select start_time from run where id = $RunID;"
   },
   {
    "name": "EndTime",
    "query": "select end_time from run where id = $RunID;"
   },
   {
    "name": "IncidentType",
    "query": "select incident_type from incident where run_id = $RunID;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<p style = \"font-family:Broadway;font-size:200%;text-align:center;weight:bold;color:#0000cc;background-color:white\">Reliability Monitoring Dashboad</p>\n\n\n\n\n\n"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  build_details AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  release AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  description AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  run_type AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  name AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  run_status AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  environment AS metric,\n  id\nFROM run\nWHERE\n  id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Iteration Status Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none", "label": "Iterations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Iteration Status Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'COMPLETED' AND\n  run_id = $RunID\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'FAILED' AND\n  run_id = $RunID\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\n  end_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(end_time) AND\n  status = 'STARTED' AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Iteration Status Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  status AS metric,\n  lock_id\nFROM iteration\nWHERE\n  $__timeFilter(start_time) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Incidents Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  status AS metric,\n  iteration_number\nFROM iteration\nWHERE\n  $__timeFilter(start_time) AND\n  status = 'FAILED' AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Incident Type Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_of_occurance AS \"time\",\n  incident_type AS metric,\n  iteration_id\nFROM incident\nWHERE\n  $__timeFilter(time_of_occurance) AND\n  incident_type = '$IncidentType' AND\n  run_id = $RunID\nORDER BY incident_type"
    }
   ]
  },
  {
   "title": "Incident  Type Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  time_of_occurance AS \"time\",\n  incident_type AS metric,\n  id\nFROM incident\nWHERE\n  $__timeFilter(time_of_occurance) AND\n  incident_type = '$IncidentType'\nORDER BY incident_type"
    }
   ]
  },
  {
   "title": "Iteration Status Over Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none", "label": "Counts" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  status AS metric,\n  id\nFROM iteration\nWHERE\n  $__timeFilter(start_time) AND\n  run_id = $RunID\nORDER BY 1,2"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  id AS \"id\"\nFROM iteration\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  start_time AS \"time\",\n  id AS \"id\"\nFROM iteration\nWHERE\n  $__timeFilter(start_time)\nORDER BY 1,2\n"
    }
   ]
  }
 ]
}