{
 "title": "dashboard",
 "description": "test",
 "time": { "from": "2018-09-18T08:41:52.625Z", "to": "2018-09-18T09:21:56.521Z" },
 "panels": [
  {
   "title": "Chi Tiết Nhân Viên",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"NhanVien\".\"HoTenNV\" as \"Họ Tên Nhân Viên\" ,\"MucTieu\".\"SoMT\" as \"Muc tiêu Tuần\",\r\n\r\n\"HoanThanh\".\"SoHT\" as \"Hoàn Thành Tuần\", \"HoanThanh\".\"SoHT\"/\"MucTieu\".\"SoMT\"*100 as \"% Tuần\"\r\n\r\nFROM public.\"NhanVien\",public.\"MucTieu\",public.\"HoanThanh\"\r\n\r\nwhere public.\"NhanVien\".\"MaNV\"=public.\"MucTieu\".\"MaNV\" and public.\"NhanVien\".\"MaNV\"=public.\"HoanThanh\".\"MaNV\" \r\n      \r\n      and public.\"MucTieu\".\"MaMT\" like '%Tuan%' and public.\"HoanThanh\".\"MaHT\" like '%Tuan%'\r\n\r\n\r\n"
    },
    {
     "rawSql": "SELECT \"NhanVien\".\"HoTenNV\" as \"Họ Tên Nhân Viên\" ,\"MucTieu\".\"SoMT\" as \"Muc tiêu Tháng\",\r\n\r\n\"HoanThanh\".\"SoHT\" as \"Hoàn Thành Tháng\", \"HoanThanh\".\"SoHT\"/\"MucTieu\".\"SoMT\"*100 as \"% Tháng\"\r\n\r\nFROM public.\"NhanVien\",public.\"MucTieu\",public.\"HoanThanh\"\r\n\r\nwhere public.\"NhanVien\".\"MaNV\"=public.\"MucTieu\".\"MaNV\" and public.\"NhanVien\".\"MaNV\"=public.\"HoanThanh\".\"MaNV\" \r\n      \r\n      and public.\"MucTieu\".\"MaMT\" like '%Thang%' and public.\"HoanThanh\".\"MaHT\" like '%Thang%'"
    },
    {
     "rawSql": "SELECT \"NhanVien\".\"HoTenNV\" as \"Họ Tên Nhân Viên\" ,\"MucTieu\".\"SoMT\" as \"Muc tiêu Năm\",\r\n\r\n\"HoanThanh\".\"SoHT\" as \"Hoàn Thành Năm\", \"HoanThanh\".\"SoHT\"/\"MucTieu\".\"SoMT\"*100 as \"% Năm\"\r\n\r\nFROM public.\"NhanVien\",public.\"MucTieu\",public.\"HoanThanh\"\r\n\r\nwhere public.\"NhanVien\".\"MaNV\"=public.\"MucTieu\".\"MaNV\" and public.\"NhanVien\".\"MaNV\"=public.\"HoanThanh\".\"MaNV\" \r\n      \r\n      and public.\"MucTieu\".\"MaMT\" like '%Nam%' and public.\"HoanThanh\".\"MaHT\" like '%Nam%'"
    }
   ]
  },
  {
   "title": "Muc tiêu tuần",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \"NhanVien\".\"HoTenNV\" as \"Họ Tên Nhân Viên\" ,\"MucTieu\".\"SoMT\" as \"Muc tiêu Tuần\",\r\n\r\n\"HoanThanh\".\"SoHT\" as \"Hoàn Thành Tuần\", \"HoanThanh\".\"SoHT\"/\"MucTieu\".\"SoMT\"*100 as \"% Tuần\"\r\n\r\nFROM public.\"NhanVien\",public.\"MucTieu\",public.\"HoanThanh\"\r\n\r\nwhere public.\"NhanVien\".\"MaNV\"=public.\"MucTieu\".\"MaNV\" and public.\"NhanVien\".\"MaNV\"=public.\"HoanThanh\".\"MaNV\" \r\n      \r\n      and public.\"MucTieu\".\"MaMT\" like '%Tuan%' and public.\"HoanThanh\".\"MaHT\" like '%Tuan%'\r\n "
    }
   ]
  },
  {
   "title": "Mục Tiêu Tháng",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \"NhanVien\".\"HoTenNV\" as \"Họ Tên Nhân Viên\" ,\"MucTieu\".\"SoMT\" as \"Muc tiêu Tháng\",\r\n\r\n\"HoanThanh\".\"SoHT\" as \"Hoàn Thành Tháng\", \"HoanThanh\".\"SoHT\"/\"MucTieu\".\"SoMT\"*100 as \"% Tháng\"\r\n\r\nFROM public.\"NhanVien\",public.\"MucTieu\",public.\"HoanThanh\"\r\n\r\nwhere public.\"NhanVien\".\"MaNV\"=public.\"MucTieu\".\"MaNV\" and public.\"NhanVien\".\"MaNV\"=public.\"HoanThanh\".\"MaNV\" \r\n      \r\n      and public.\"MucTieu\".\"MaMT\" like '%Thang%' and public.\"HoanThanh\".\"MaHT\" like '%Thang%'\r\n "
    }
   ]
  },
  {
   "title": "Mục Tiêu Tháng",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \"NhanVien\".\"HoTenNV\" as \"Họ Tên Nhân Viên\" ,\"MucTieu\".\"SoMT\" as \"Muc tiêu Năm\",\r\n\r\n\"HoanThanh\".\"SoHT\" as \"Hoàn Thành Năm\", \"HoanThanh\".\"SoHT\"/\"MucTieu\".\"SoMT\"*100 as \"% Năm\"\r\n\r\nFROM public.\"NhanVien\",public.\"MucTieu\",public.\"HoanThanh\"\r\n\r\nwhere public.\"NhanVien\".\"MaNV\"=public.\"MucTieu\".\"MaNV\" and public.\"NhanVien\".\"MaNV\"=public.\"HoanThanh\".\"MaNV\" \r\n      \r\n      and public.\"MucTieu\".\"MaMT\" like '%Nam%' and public.\"HoanThanh\".\"MaHT\" like '%Nam%'\r\n "
    }
   ]
  }
 ]
}